apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
      component: mysql-server
      tier: back
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-server
        component: mysql-server
        tier: back
    spec:
      containers:
        - name: mysql-server
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.schema
      volumes:
        - name: mysql-volume
          hostPath:
            path: /volume/data/pettion