apiVersion: v1
kind: Service
metadata:
  name: mysql-server
spec:
  ports:
    - name: mysql-server
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql-server
    component: mysql-server
  clusterIP: None
