apiVersion: apps/v1
kind: Deployment
metadata:
  name: pettion-react
  labels:
    app: pettion-react
    tier: front
spec:
  selector:
    matchLabels:
      app: pettion-react
      tier: front
  replicas: 1
  template:
    metadata:
      labels:
        app: pettion-react
        tier: front
    spec:
      containers:
        - name: pettion-react
          image: phjppo0918/pettion-react:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pettion-react
spec:
  type: NodePort
  selector:
    app: pettion-react
    tier: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31313
