apiVersion: apps/v1
kind: Deployment
metadata:
  name: pettion-react
spec:
  selector:
    matchLabels:
      app: pettion-react
      tier: front
  replicas: 1
  template:
    metadata:
      labels:
        app: pettion-react
        tier: front
    spec:
      containers:
        - name: pettion-react
          image: phjppo0918/pettion-react
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pettion-react
spec:
  type: NodePort
  selector:
    app: pettion-react
    tier: front
  ports:
    - port: 8083
      targetPort: 80
      protocol: TCP
      nodePort: 31313