apiVersion: v1
kind: Service
metadata:
  name: pettion-react
spec:
  type: NodePort
  selector:
    app: pettion-react
    tier: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31313
