apiVersion: apps/v1
kind: Deployment
metadata:
  name: pettion-server
spec:
  selector:
    matchLabels:
      app: pettion-server
      component: pettion-server
      tier: back
  replicas: 1
  template:
    metadata:
      labels:
        app: pettion-server
        component: pettion-server
        tier: back
    spec:
      containers:
        - name: pettion-server
          image: phjppo0918/pettion-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.port
            - name: DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.schema
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.password
          resources:
            requests:
              cpu: "250m"
              memory: "4Gi"
            limits:
              cpu: "500m"
              memory: "8Gi"
